version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - skillverse-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_URI=postgresql://skillverse_user:skillverse_pass@postgres:5432/skillverse_db
      - MONGO_URI=mongodb://mongo:27017/skillverse
    depends_on:
      - postgres
      - mongo
    networks:
      - skillverse-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skillverse_db
      - POSTGRES_USER=skillverse_user
      - POSTGRES_PASSWORD=skillverse_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - skillverse-network

  mongo:
    image: mongo:7-jammy
    environment:
      - MONGO_INITDB_DATABASE=skillverse
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - skillverse-network

volumes:
  postgres_data:
  mongo_data:

networks:
  skillverse-network:
    driver: bridge
