apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillverse-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skillverse-frontend
  template:
    metadata:
      labels:
        app: skillverse-frontend
    spec:
      containers:
        - name: frontend
          image: skillverse-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skillverse-frontend
spec:
  type: LoadBalancer
  selector:
    app: skillverse-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
