apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillverse-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillverse-mongo
  template:
    metadata:
      labels:
        app: skillverse-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: skillverse
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: skillverse-mongo-service
spec:
  selector:
    app: skillverse-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
